# baseURL = 'https://example.org/'
# locale = 'en-us'
# title = 'My New Hugo Project'

baseURL = 'https://seekeren.github.io/'
languageCode = 'zh-CN'
title = 'seekeren blog'
theme = "void"

[params]
  [params.social]
    github = "https://github.com/seekeren"
    email = "1786723244@qq.com"
  [params.avatar]
    url = "https://avatars.githubusercontent.com/seekeren"

[[menus.main]]
name = '首页'
pageRef = '/'
weight = 10

[[menus.main]]
name = '开发记录'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = '标签'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = '关于'
pageRef = '/about'
weight = 40

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true